if (WIN32)
    set(MATRIX_OS_WIN ON)
elseif (APPLE)
    set(MATRIX_OS_APPLE ON)

    if (IOS OR CMAKE_SYSTEM_NAME STREQUAL iOS)
        set(MATRIX_OS_IOS ON)
    else()
        set(MATRIX_OS_MACOS ON)
    endif()
else()
    set(MATRIX_OS_UNIX ON)

    if (ANDROID OR CMAKE_SYSTEM_NAME MATCHES "Android")
        set(MATRIX_OS_ANDROID ON)
    elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
        set(MATRIX_OS_LINUX ON)
    elseif(CMAKE_SYSTEM_NAME STREQUAL FreeBSD)
        set(MATRIX_OS_FREEBSD ON)
    endif()
endif()


if (MATRIX_OS_WIN)
    add_definitions(-DWIN32 -DMATRIX_OS_WIN)
elseif(MATRIX_OS_APPLE)
    add_definitions(-DMATRIX_OS_APPLE)

    if (MATRIX_OS_IOS)
        add_definitions(-DMATRIX_OS_IOS)
    else()
        add_definitions(-DMATRIX_OS_MACOS)
    endif()

    if (MATRIX_ARM)
        set(WITH_SECURE_JIT ON)
    endif()
elseif(MATRIX_OS_UNIX)
    add_definitions(-DMATRIX_OS_UNIX)

    if (MATRIX_OS_ANDROID)
        add_definitions(-DMATRIX_OS_ANDROID)
    elseif (MATRIX_OS_LINUX)
        add_definitions(-DMATRIX_OS_LINUX)
    elseif (MATRIX_OS_FREEBSD)
        add_definitions(-DMATRIX_OS_FREEBSD)
    endif()
endif()

if (WITH_SECURE_JIT)
    add_definitions(-DXMRIG_SECURE_JIT)
endif()
